using System;
using UnityEngine;

namespace Gamebeast.Internal
{
    /// <summary>
    /// Resolves the distinct id for this session. When the developer does not supply
    /// one, an anonymous id is generated once and persisted in PlayerPrefs so the
    /// same device reports as the same user across sessions.
    /// </summary>
    internal sealed class DistinctIdentity
    {
        private const string PlayerPrefsKey = "Gamebeast.AnonymousDistinctId";

        public string DistinctId { get; }

        /// <summary>True when the id was generated by the SDK rather than supplied by the developer.</summary>
        public bool IsAnonymous { get; }

        private DistinctIdentity(string distinctId, bool isAnonymous)
        {
            DistinctId = distinctId;
            IsAnonymous = isAnonymous;
        }

        public static DistinctIdentity Resolve(string explicitDistinctId)
        {
            if (!string.IsNullOrWhiteSpace(explicitDistinctId))
            {
                return new DistinctIdentity(explicitDistinctId.Trim(), isAnonymous: false);
            }

            // Keep the stored anonymous id stable even if a developer-supplied id is
            // used in some sessions, so anonymous sessions always map to the same user.
            var stored = PlayerPrefs.GetString(PlayerPrefsKey, string.Empty);
            if (string.IsNullOrEmpty(stored))
            {
                stored = Guid.NewGuid().ToString("N");
                PlayerPrefs.SetString(PlayerPrefsKey, stored);
                PlayerPrefs.Save();
                GBLog.Info($"Generated anonymous distinct id '{stored}'.");
            }

            return new DistinctIdentity(stored, isAnonymous: true);
        }
    }
}
